// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Currency struct {
	ID int64 `json:"id"`
	// ISO 4217
	Code      string    `json:"code"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID         int64 `json:"id"`
	UserID     int64 `json:"user_id"`
	CurrencyID int64 `json:"currency_id"`
	// can be negative(can be negative(withdrawal) or positive(deposit)
	Amount     int64     `json:"amount"`
	TimePlaced time.Time `json:"time_placed"`
	CreatedAt  time.Time `json:"created_at"`
}
