// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateCurrency(ctx context.Context, code string) (Currency, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	GetBalance(ctx context.Context, userID int64) ([]GetBalanceRow, error)
	GetCurrencyByCode(ctx context.Context, code string) (Currency, error)
	GetCurrencyByID(ctx context.Context, id int64) (Currency, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
}

var _ Querier = (*Queries)(nil)
